---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: eurotransit
spec:
  encryptedData:
    password: AgA//YNHqvPk4o/fG9S0SFuCCqH5vy1LItXFR2aufvq67LV8oNa2V/WTHQCuLM9OBs3aFypAk20hH6+wUOYn1jDYXdW1XwwBLSvkZiiGiLwQPo4w4Bpz0fbNjQ/HfqIM/3NFcejNnRnqgWEVBTgdu9RizSS0PM+MSiez731MLEnUtN+dpR/FV6BaDLkjSBNwPanrWlOCDFs35YZBC5/hmAOuG+cQFuchee8tVEaM6BPUL3POoRCyxTe7lIDMgmPKaJLyat/vuiIhqwSIhD70BLWnTI4KRga5cPqIkiu24KWINX4XyWLurKe/vnCZ/mgnj4SLxXkUrugcVQz5umfuYNAgGiT4aztmnHRuGXAMms8EpJft/xErHtYEzlFtkoeS1nQqeqFSA9tMiQrQvjG5e41XeDMI9TzFG73hUPocc15VR8ESWa7K+LU51ygkdCw+GIaRXmMgAPQ/OLqOS+DrP5x+FwgQ3UdYkrBR1KZrpvWBY7nR/32tI+vJaXfjH6NM355n3gArMFZ9Rk5jJ3JsgDkXaqYBbBLrhPvd9y4MVt4ivtvCvnK9X/UXHHBYhCnStKTZEzIXeeatljJOT3N2dwo33Wn8E04a8URIiO5L0PkxgLEyQ7GQTaZsEImQx0hnnW8eBr2/cBXdsAM1eK8rLGfG3v14TKhJLOqTVayidn5kmdmluM4kxgrkC9k34hgs3vb2N0I9ZsEj9gfI/emIZTTsT8c3uO8XCwwshVIpjCqalg==
    username: AgACaHE5+reQufzpAXWfKqh0/Csq6xb1l8t9XSSX7SF2lB2qAFRJBm7PuyXLonRJiRWcE3OY7pQ3DbjQb2E+qkLWdDYVl3+kpNCNE8t3GBWmGVO6cYTPX1H7ZQrIkgNiHyzrWP76KF6kqigm215wspGmuzn0+d+GvgW5H39+grvzEbl133lss4pQHCcgp/dShq0dkD7skSyzrDPzUZ9nWvsTwx8sjKkoLh7nfQX9mO5M16zIGRsKbSoaB1N7qU2J6buOdS9pLezgB1v5LBTUK+1nD9vXPYoQw8zRH76O4cXXWrmbEyEN7RjIZXHiLG0u64kIpkc3wK3TpkOpefDRRXeyWa4F3Wgkomkig9Z/SP2b58CQqWt+b+Xzy8mOGbdslxSKRXUS5Q4sI+S2calyD8NUhfM4lurN3ulnhGAqSwKmbckdxpsTP+x9Ce/vrQaOKp1cWBKXMOzbBAfZuu9CGHQ1yBm4+feIK355Am9rE1jAvSizDrmQNZVVNGfHOkUAX0k03Id+uXB00WzSEnP3F5e/ECyUXsqonGUkVrlkBB3lRTCNN74za2AYdr+i1rpk+Ue7/ZYKHVJXKazVo27P3adEmixA4kUE5XZjugbNTkxcp9Re/eTF6kzC3B1lAL//uPzmBkF2i0zasjwuWKYiwZ+dZnPBZeOjfMSpll/hrRyWWJTjl9lDhOi4Dii5VAQSfPoILypyDA==
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: eurotransit
