{{- $strategy := include "eurotransit.deploymentStrategy" (dict "root" . "service" "frontend") | trim -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eurotransit.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if ne $strategy "standard" }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- end }}
spec:
  replicas: {{ ternary .Values.frontend.replicaCount 0 (eq $strategy "standard") }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        kubectl.kubernetes.io/restartedAt: "{{ .Values.frontend.restartedAt }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ include "eurotransit.imageReference" .Values.frontend.image }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
