{{- if .Values.canary.orders.enabled }}
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: {{ include "eurotransit.fullname" . }}-orders-canary
  namespace: {{ .Values.namespace }}
spec:
  weighted:
    services:
      - name: {{ default (printf "%s-orders" (include "eurotransit.fullname" .)) .Values.canary.orders.stableServiceName }}
        port: {{ .Values.orders.service.port }}
        weight: {{ .Values.canary.orders.stableWeight }}
      - name: {{ .Values.canary.orders.canaryServiceName }}
        port: {{ .Values.orders.service.port }}
        weight: {{ .Values.canary.orders.canaryWeight }}
{{- end }}
