{{- if .Values.zipkin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eurotransit.fullname" . }}-zipkin
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.zipkin.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: zipkin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zipkin
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: zipkin
          image: "{{ .Values.zipkin.image.repository }}:{{ .Values.zipkin.image.tag }}"
          imagePullPolicy: {{ .Values.zipkin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9411
              protocol: TCP
          resources:
            {{- toYaml .Values.zipkin.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eurotransit.fullname" . }}-zipkin
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.zipkin.service.type }}
  ports:
    - port: {{ .Values.zipkin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
