apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eurotransit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CPO-G02/eurotransit-configuration-g02
    targetRevision: main
    path: deploy/charts/eurotransit
  destination:
    server: https://kubernetes.default.svc
    namespace: eurotransit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
